---
title: "AI가 만능이 아닌 이유"
description: |
  AI가 사회과학 분야에서 역할을 할 수 있을까?
categories:
  - AI
author:
  - name: Jongseon, Han
    url: https://hanjongseon.github.io
    orcid_id: 0000-0002-4148-9290
date: 05-27-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- 사람들은 알파고 이후, 세상의 모든 문제를 AI가 해결해줄 것이라 생각했다. 바둑의 그 수많은 경우의 수를 해결할 정도니까 일상의 대부분 문제도 AI가 대체해 줄 것이라 믿었다.<br>
그러나 생각해보면 우리 일상에서 IT 쪽 기기 뺴고는 AI가 하는 일이 없다. 왜일까?<br>

- AI가 마치 스스로의 지능이 있는 것처럼 느껴지는 경우가 있지만, 결국은 미리 계산된 수학적인 확률에 근거해서 방향성을 예측하는 것 뿐이다. 그런데 인간이 하는 직관적인 판단, 행동이 이것과는 조금 거리가 있다. 수학적인 계산, 합리성과는 거리가 있는 경우가 진짜 더럽게 많다.<br>

- 도덕적인 행동은 수학적인 계산에 의해서 이루어지는가? 사람들이 차가 없는 횡단보도를 몰라서 안 건너는가? 사람들이 주식을 살 때, 20년치의 하루하루 가격과 거래량을 보고 수학적 판단을 내려서 결정을 내리는가? 모두가 아니다이다. <br>

- 사람들은 경험, 감정, 사회적 합의 등에 의해서 휴리스틱 기반의 직관적인 판단을 하는 경우가 너무나도 많다. 그리고 그것들이 비합리적인 경우도 있지만 꽤나 장기적으로 효과적인 경우도 있다. 개인이나 사회에 따라서 달라지고 똑같은 상황에서도 결정이 달라지는 경우가 수도 없이 있다. 일관성 따위가 없다. 어쩔 때는 좋은 대안인 경우도 있고 왜 그런 짓을 하는지 모르는 경우가 있을 때도 있다. 추가로 그 직관적인 판단이 동일한 사람임에도 별다른 이유 없이 다른 판단으로 나타날 때도 있다.<br>

- 쉽게 말해서 애초에 일관성도 없고 답도 없는 문제(너무 많은 변수가 존재하는 문제)를 AI가 해결해 줄 것이라고 믿는 것이다. 가끔 사람들의 개인감정같은 부분까지 패턴을 파악하면 된다는 인간들이 있는데 그 데이터를 구축하는 게 말이 되는 이야기라고 생각하는 것인지 이해할 수가 없다. AI는 결국 필요한 데이터를 얼마나 많이 모으냐에 해답이 있다. 머신러닝 같은 건 데이터만 제대로 되어 있으면 회귀 분석만 해도 그럴싸하게 나온다. 사람 신경계의 화학물질을 데이터화할 수 있을 것 같은가? 세상의 모든 변수를 데이터화할 수 있을 것 같은가? 기술이 아무리 발전해도 데이터 수집 단계부터 불가능한 영역이다.<br>

- 앞으로도 AI는 경제, 정치, 법, 문화 등 전반적인 사회과학 분야에서 별다른 기능을 하지 못할 것이다. 애초에 데이터 구축이 불가능하며 AI가 정확하고 합리적인 판단을 내려준다 한들, 사람들은 따르지 않을 것이기에...