---
title: "g2r"
description: |
  New and useful visualization packages
categories:
  - R
  - Visualization
preview: https://user-images.githubusercontent.com/24967549/110570815-e3fe3800-8199-11eb-93d3-19673f277702.PNG
author:
  - name: Jongseon, Han
    url: https://hanjongseon.github.io
    orcid_id: 0000-0002-4148-9290
date: 03-03-2021
output:
  distill::distill_article:
    self_contained: false
---


- interactive plot 패키지로 g2r이 나왔다. 아직 완성도가 있다고 보기는 어렵지만 plotly에 비하면 훨씬 직관적이고 이해하기 좋다. ggplot에서 그 방향성은 유지된 것으로 보인다. 방법적인 측면에서 거의 유지가 되었기 때문에 ggplot을 사용하던 사람들의 입장에서 보면 일단 배우기가 쉽다고 보면 된다.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- 아래는 해당 패키지의 [`공개 예제`](https://g2r.opifex.org/index.html?fbclid=IwAR3NrNikgTn-9xIeNdCAkPkZGcqierfL2gZMJ7879sjiFjOSuBWdk9VDDaE)이다.

```r
# install.packages("remotes")
remotes::install_github("devOpifex/g2r")
```

```{r, preview=TRUE}
library(g2r)
json <- jsonlite::fromJSON(
  "https://gw.alipayobjects.com/os/antvdemo/assets/data/baby-names.json"
)

json %>%
  dplyr::group_by(name, year) %>%
  dplyr::summarise(n = sum(n)) %>%  
  g2(asp(year, n, color = name, shape = "smooth")) %>% 
  fig_area(
    adjust("stack"), adjust("symmetric"),
    fillOpacity = .85
  ) %>% 
  gauge_x_linear(tickInterval = 20) %>% 
  legend_color(position = "right")

```

