---
title: "[R] disk.frame"
description: |
  about disk.frame
categories:
  - R
  - parallel
author:
  - name: Jongseon, Han
    url: https://hanjongseon.github.io
date: 03-19-2021
output:
  distill::distill_article:
    #highlight: kate
    #highlight_downlit: true
    #self_contained: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<dt-code language="html">let x = 10;</dt-code>

```python
import kaggle
import os
```


```python
os.getcwd()
```




    '/home/hanjongseon/work'




```python
os.listdir()
```




    ['Untitled.ipynb',
     'WFC_POI_DATA(검토).xlsx',
     'dask-worker-space',
     'dask_parallel.ipynb',
     'Untitled1.ipynb',
     '.ipynb_checkpoints',
     'credit-card',
     'TEST_CELL_20210311.txt',
     'POI_CAMBODIA_공감랩_20210223_화.xlsx']




```python
os.listdir("./")
```




    ['Untitled.ipynb',
     'WFC_POI_DATA(검토).xlsx',
     'dask-worker-space',
     'dask_parallel.ipynb',
     'Untitled1.ipynb',
     '.ipynb_checkpoints',
     'credit-card',
     'TEST_CELL_20210311.txt',
     'POI_CAMBODIA_공감랩_20210223_화.xlsx']




```python
import time
import modin.pandas as pd
import pyspark
from pyspark.sql import SparkSession
```


```python
%%time
df = pd.read_csv('TEST_CELL_20210311.txt', sep= "|")
```

    CPU times: user 2.5 s, sys: 723 ms, total: 3.23 s
    Wall time: 8.27 s



```python
len(df)
```




    43126022




```python
spark = SparkSession.builder \
...     .master("local[*]") \
...     .appName("Word Count") \
...     .config("spark.some.config.option", "some-value") \
...     .getOrCreate()
```


```python
%%time
df2 = spark.read\
        .options(header=True, inferSchema=True, sep= "|").csv('TEST_CELL_20210311.txt')
```

    CPU times: user 2.3 s, sys: 313 ms, total: 2.61 s
    Wall time: 45 s



```python
df2.count()
```




    43126022




```python
%%time
df
```

    CPU times: user 2 us, sys: 0 ns, total: 2 us
    Wall time: 3.34 us





<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>CELL_ID</th>
      <th>LON</th>
      <th>LAT</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>5d64b3139e5500005e002272</td>
      <td>104.189400</td>
      <td>12.068550</td>
    </tr>
    <tr>
      <th>1</th>
      <td>5d64b3139e5500005e002273</td>
      <td>104.189400</td>
      <td>12.068360</td>
    </tr>
    <tr>
      <th>2</th>
      <td>5d64b3139e5500005e002274</td>
      <td>104.189400</td>
      <td>12.068170</td>
    </tr>
    <tr>
      <th>3</th>
      <td>5d64b3139e5500005e002275</td>
      <td>104.189400</td>
      <td>12.067980</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5d64b3139e5500005e002276</td>
      <td>104.189400</td>
      <td>12.067790</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>43126017</th>
      <td>5f86b07e641f0000f2921564</td>
      <td>104.433534</td>
      <td>11.130932</td>
    </tr>
    <tr>
      <th>43126018</th>
      <td>5f86b07e641f0000f2921565</td>
      <td>104.433719</td>
      <td>11.130932</td>
    </tr>
    <tr>
      <th>43126019</th>
      <td>5f86b07e641f0000f2921566</td>
      <td>104.433905</td>
      <td>11.130932</td>
    </tr>
    <tr>
      <th>43126020</th>
      <td>5f86b07e641f0000f2921567</td>
      <td>104.434090</td>
      <td>11.130932</td>
    </tr>
    <tr>
      <th>43126021</th>
      <td>5f86b07e641f0000f2921568</td>
      <td>104.434276</td>
      <td>11.130932</td>
    </tr>
  </tbody>
</table>
<p>43126022 rows x 3 columns</p>
</div>




```python
%%time
df2.show()
```

    +--------------------+--------+--------+
    |             CELL_ID|     LON|     LAT|
    +--------------------+--------+--------+
    |5d64b3139e5500005...|104.1894|12.06855|
    |5d64b3139e5500005...|104.1894|12.06836|
    |5d64b3139e5500005...|104.1894|12.06817|
    |5d64b3139e5500005...|104.1894|12.06798|
    |5d64b3139e5500005...|104.1894|12.06779|
    |5d64b3139e5500005...|104.1894| 12.0676|
    |5d64b3139e5500005...|104.1894|12.06741|
    |5d64b3139e5500005...|104.1894|12.06722|
    |5d64b3139e5500005...|104.1894|12.06703|
    |5d64b3139e5500005...|104.1894|12.06684|
    |5d64b3139e5500005...|104.1894|12.06665|
    |5d64b3139e5500005...|104.1894|12.06646|
    |5d64b3139e5500005...|104.1894|12.06627|
    |5d64b3139e5500005...|104.1894|12.06608|
    |5d64b3139e5500005...|104.1894|12.06589|
    |5d64b3139e5500005...|104.1894| 12.0657|
    |5d64b3139e5500005...|104.1894|12.06551|
    |5d64b3139e5500005...|104.1894|12.06532|
    |5d64b3139e5500005...|104.1894|12.06513|
    |5d64b3139e5500005...|104.1894|12.06494|
    +--------------------+--------+--------+
    only showing top 20 rows
    
    CPU times: user 0 ns, sys: 9.56 ms, total: 9.56 ms
    Wall time: 65.6 ms



```python
%%time
A = df[df.LON<104]
len(A)
```

    CPU times: user 1.17 s, sys: 388 ms, total: 1.56 s
    Wall time: 1.89 s





    2599411




```python
%%time
B = df2[df2.LON<104]
B.count()
```

    CPU times: user 1.33 s, sys: 155 ms, total: 1.49 s
    Wall time: 27.4 s





    2599411




```python
df2.describe().show()
```

    +-------+--------------------+-------------------+------------------+
    |summary|             CELL_ID|                LON|               LAT|
    +-------+--------------------+-------------------+------------------+
    |  count|            43126022|           43126022|          43126022|
    |   mean|                null| 104.52575814540062|11.229103856772703|
    | stddev|                null|0.36150442929482013| 0.394896269663501|
    |    min|5d64b3139e5500005...|           103.7737|      10.411592004|
    |    max|5f86b07e641f0000f...|           105.2963|          12.07653|
    +-------+--------------------+-------------------+------------------+
    



```python

```

