---
title: "확률 가중 함수와 가치함수_작성중"
description: |
  Behavioral economics:Probability-weighted and value functions
categories:
  - Probability Weighted Function
  - Value function
  - Behavioral economics
  - R
author:
  - name: Jongseon, Han
    url: https://hanjongseon.github.io
date: 03-05-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- 행동 경제학에는 확률가중함수와 가치함수라는 것이 존재한다.<br/>
자세한 내용들은 서적이나 검색을 통해 알 수 있겠지만, 간단히 설명하면 아래와 같다.

><u>**확률가중함수**</u><br/>확률에 대해 사람들이 가중치를 두어 생각한다는 것을 보여주는 함수<br/>
><u>**가치함수**</u><br/>사람의 손실회피 성향을 보여주는 것으로, 손실에 대해서 더 많은 가치 부여를 보이는 경향을 보임



```{r}

#확률 가중 함수
w_p = function(p,r=0.65){
  if(p<0){
    k = p * (-1)
    return((k**r)/((k**r)+(1-k)**r)**(1/r)*(-1) * 2.25)
  }
  if(p>0){
    return((p**r)/((p**r)+(1-p)**r)**(1/r))
  }
  if(p==0){
    return(0)
  }
}

# 가치 함수
value_f = function(x){
    if(x>=0){
        y = x**0.88
    }
    if(x<0){
        y = -2.25*(-x)**0.88
    }
    return(y)
}

#확률리스트 생성
p_list = seq(0,1,by=0.01)
p_df = data.frame(p_list)
p_df$W_P = unlist(Map(w_p, p_list))
head(p_df)

library(ggplot2)
ggplot() + geom_point(data=p_df, aes(x=1:nrow(p_df), y=p_list), col='blue')+
  geom_point(data=p_df, aes(x=1:nrow(p_df), y=W_P), col='red')+
  xlab('real prob(%)')+
  ylab('Probability of feeling') + theme_bw()

```



Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


